#!/bin/bash
#===============================================================================
# DIRECTORY:
#   ---
#
# FILE:
#   04_qemu-nautilus-scripts_installer
#
# USAGE:
#   bash 04_qemu-nautilus-scripts_installer
#
# OPTIONS:
#   none
#
# DESCRIPTION:
#   Installs qemu-nautilus-scripts...
#
# REQUIREMENTS:
#   bash, ...
#
# BUGS:
#   ---
#
# NOTES:
#   Tested on Debian 8.
#
# AUTHOR:
#   Patrick Neumann, patrick@neumannsland.de
#
# COMPANY:
#   (privately)
#
# VERSION:
#   0.9 (beta)
#
# LINK TO THE MOST CURRENT VERSIONS:
#   https://raw.githubusercontent.com/casualscripter/debian-stuff/master/
#
# CREATED:
#   02.04.2016
#
# COPYRIGHT (C):
#   2015-2016 - Patrick Neumann
#
# LICENSE:
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
# WARRANTY:
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# TODO:
#   - more DRY (don't repeat yourself)
#
# HISTORY:
#   0.9 - Patrick Neumann - Initial (public) release
#
#===============================================================================

#=== CONFIGURATION =============================================================
WHICH_BIN="/usr/bin/which"                                  # Debian 8.x default
PRINTF_BIN="$( ${WHICH_BIN} printf )"
SUDO_BIN="$( ${WHICH_BIN} sudo )"                       # needs configured sudo!
APTITUDE_BIN="$( ${WHICH_BIN} aptitude )"
SLEEP_BIN="$( ${WHICH_BIN} sleep )"
EXPR_BIN="$( ${WHICH_BIN} expr )"
CAT_BIN="$( ${WHICH_BIN} cat )"
PGREP_BIN="$( ${WHICH_BIN} pgrep )"
GNOMESHELL_BIN="$( ${WHICH_BIN} gnome-shell )"
MKDIR_BIN="$( ${WHICH_BIN} mkdir )"
WGET_BIN="$( ${WHICH_BIN} wget )"
UNZIP_BIN="$( ${WHICH_BIN} unzip )"
RM_BIN="$( ${WHICH_BIN} rm )"
SU_BIN="$( ${WHICH_BIN} su )"
GREP_BIN="$( ${WHICH_BIN} grep )"
GROUPS_BIN="$( ${WHICH_BIN} groups )"
USERMOD_BIN="$( ${SUDO_BIN} ${WHICH_BIN} usermod )"     # needs configured sudo!
GSQ_BIN="$( ${WHICH_BIN} gnome-session-quit )"

#=== FUNCTION ==================================================================
# NAME: error_exit
# DESCRIPTION: Display red error messages surrounded by "ERROR:" and "EXIT!!!".
# PARAMETER 1: message (string)
#===============================================================================
error_exit () {
  "${PRINTF_BIN}" "\n\033[01;31;40mERROR: ${1}... EXIT!!!\033[00m\n\n"
  exit 1
}

#=== FUNCTION ==================================================================
# NAME: error
# DESCRIPTION: Display red error messages starting with "ERROR:".
# PARAMETER 1: message (string)
#===============================================================================
error () {
  "${PRINTF_BIN}" "\033[01;31;40mERROR: ${1}!!!\033[00m\n"
}

#=== FUNCTION ==================================================================
# NAME: hint
# DESCRIPTION: Display blue hint messages starting with "HINT:".
# PARAMETER 1: message (string)
#===============================================================================
hint () {
  "${PRINTF_BIN}" "\033[01;34;40mHINT: ${1}!\033[00m\n"
}

#=== FUNCTION ==================================================================
# NAME: success
# DESCRIPTION: Display green success messages starting with "SUCCESS:".
# PARAMETER 1: message (string)
#===============================================================================
success () {
  "${PRINTF_BIN}" "\033[01;32;40mSUCCESS: ${1}!\033[00m\n"
}

#-------------------------------------------------------------------------------
# Check vor Debian GNU/Linux.
#-------------------------------------------------------------------------------
if ! [ -f "/etc/debian_version" ] ; then
  error_exit "Debian GNU/Linux not found"
fi

#-------------------------------------------------------------------------------
# Check vor Version 8 (jessie) or greater.
#-------------------------------------------------------------------------------
if ! ${EXPR_BIN} "$( ${CAT_BIN} /etc/debian_version )" \>= 8.0 > /dev/null 2>&1 ; then
  error_exit "Debian GNU/Linux >= 8.0 not found"
fi

#-------------------------------------------------------------------------------
# Check vor a running Gnome desktop environment.
#-------------------------------------------------------------------------------
if ! ${PGREP_BIN} --full "${GNOMESHELL_BIN}" > /dev/null 2>&1 ; then
  error_exit "Gnome desktop environment not running"
fi

###

if [ ! -d "${HOME}/Downloads" ] ; then
  mkdir "${HOME}/Downloads"
fi
cd "${HOME}/Downloads"
${WGET_BIN} --timestamping https://github.com/casualscripter/qemu-nautilus-scripts/archive/master.zip
unzip master.zip
# keine anderen nautilus skripte löschen, sondern dazu kopieren!
cd qemu-nautilus-scripts-master/
for pattern in ./* ./.[!.]* ; do
  mv "${pattern}" "${HOME}/.local/share/nautilus/scripts/"
done
cd ..
rmdir qemu-nautilus-scripts/
rm master.zip
sudo chown -R "$( id -un )":"$( id -gn )" "${HOME}/.local/share/nautilus/scripts/"
sudo chmod -R 755 "${HOME}/.local/share/nautilus/scripts/"

# hinweis: kann dauern!
if [ ! "${HOME}/.local/share/nautilus/scripts/02_dd/.PALADIN_EDGE_14.04.iso" ] ; then
  SHA1="e0695b74281a63d8064b0862c1cb792ff9ba950f"
  wget --timestamping --directory-prefix="${HOME}/.local/share/nautilus/scripts/02_dd/" "ftp://ftp.domain-ermittlung.de/${SHA1}.iso"
  if [ "$( openssl dgst sha1 "${SHA1}.iso" | awk '{ print $NF; }' )" = "${SHA1}" ] ; then
	  mv "${SHA1}.iso" "${HOME}/.local/share/nautilus/scripts/02_dd/.PALADIN_EDGE_14.04.iso"
	fi
fi

# if test -f
mv "${HOME}/QEMU/OSX/Enoch-rev.2795_boot" "${HOME}/.local/share/nautilus/scripts/04_boot/.Enoch-rev.2795_boot"

# if test -f
mv "${HOME}/QEMU/OVMF/OVMF.fd" "${HOME}/.local/share/nautilus/scripts/04_boot/.OVMF.fd"

# if test -f
mkdir "${HOME}/.local/share/nautilus/scripts/04_boot/.shared_folder/"
mv "${HOME}/QEMU/QXL/*" "${HOME}/.local/share/nautilus/scripts/04_boot/.shared_folder/"

exit 0