#!/bin/bash
#===============================================================================
# FILE:         /usr/local/sbin/clean_upgrade
#
# USAGE:        $ sudo clean_upgrade
#   OR          # clean_upgrade
# OPTIONS:      none
#
# DESCRIPTION:  Automation of repetitive administrative activities relating to
#                 the maintenance of a Debian GNU/Linux system.
#                 (It should also run on a Ubuntu system!?)
#
# REQUIREMENTS: coreutils (id and echo), grep, sed, aptitude, apt-file,
#                 gawk or mawk und findutils
# BUGS:         ---
# NOTES:        ---
# AUTHOR:       Patrick Neumann, patrick@neumannsland.de
# COMPANY:      (privately)
#
# VERSION:      1.0 (stable)
# CREATED:      01.06.2015
#
# COPYRIGHT:    ---
# LICENSE:      ---
#
# HISTORY:      1.0 - Patrick Neumann - Initial (public) release
#===============================================================================

#=== FUNCTION ==================================================================
# NAME: error
# DESCRIPTION: Display red error messages surrounded by "Error" and "EXITING".
# PARAMETER 1: message (string)
#===============================================================================
function error () {
  /bin/echo -e "\033[01;31mError: ${1} . . . EXITING ! ! !\033[01;00m"
}

#-------------------------------------------------------------------------------
# Check, for root privileges.
#-------------------------------------------------------------------------------
if [[ 0 -ne "$( /usr/bin/id --user )" ]] ; then
  error "you need to be root"
  exit 1
fi

#-------------------------------------------------------------------------------
# The mother (Debian GNU/Linux) prefer "aptitude" over "apt-get".
#-------------------------------------------------------------------------------
if [ ! -x "/usr/bin/aptitude" ] ; then
  /usr/bin/apt-get update
  /usr/bin/apt-get install aptitude --assume-yes
fi

#-------------------------------------------------------------------------------
# Resynchronize the package index files from their sources (aptitude).
#-------------------------------------------------------------------------------
/usr/bin/aptitude update

#-------------------------------------------------------------------------------
# Install "deborphan" if missing.
#-------------------------------------------------------------------------------
if [ ! -x "/usr/bin/deborphan" ] ; then
  echo /usr/bin/aptitude install deborphan --assume-yes
fi

#-------------------------------------------------------------------------------
# Install "apt-file" if missing.
#-------------------------------------------------------------------------------
if [ ! -x "/usr/bin/apt-file" ] ; then
  /usr/bin/aptitude install apt-file -assume-yes
fi

#-------------------------------------------------------------------------------
# Resynchronize the package index files from their sources (apt-file).
#-------------------------------------------------------------------------------
/usr/bin/apt-file update

#-------------------------------------------------------------------------------
# Upgrading the HOLE system.
#-------------------------------------------------------------------------------
/usr/bin/aptitude dist-upgrade

#-------------------------------------------------------------------------------
# Clean local apt package cache.
#-------------------------------------------------------------------------------
/usr/bin/aptitude autoclean

#-------------------------------------------------------------------------------
# Purge icompletely deleted packages.
#-------------------------------------------------------------------------------
/usr/bin/dpkg --get-selections \
  | /bin/grep deinstall \
  | /usr/bin/awk '{ print $1; }' \
  | /usr/bin/xargs /usr/bin/aptitude purge --assume-yes

#-------------------------------------------------------------------------------
# Purge orphaned packages.
#-------------------------------------------------------------------------------
while REDUNDANT="$( /usr/bin/deborphan )" ; /usr/bin/test -n "${REDUNDANT}" ; do
  echo /usr/bin/aptitude purge "${REDUNDANT}" --assume-yes
done

exit 0
