#!/bin/bash
#===============================================================================
# DIRECTORY:
#   /usr/local/sbin/clean_upgrade
#
# FILE:
#   clean_upgrade
#
# USAGE:
#   $ sudo clean_upgrade
# OR
#   # clean_upgrade
#
# OPTIONS:
#   none
#
# DESCRIPTION:
#   Automation of repetitive administrative activities relating to
#   the maintenance of a Debian GNU/Linux system.
#
# REQUIREMENTS:
#   coreutils (id and echo), grep, sed, aptitude, apt-file,
#   gawk or mawk und findutils
#
# BUGS:
#   ---
#
# NOTES:
#   May also run on a Ubuntu system!?
#
# AUTHOR:
#   Patrick Neumann, patrick@neumannsland.de
#
# COMPANY:
#   (privately)
#
# VERSION:
#   1.0 (stable)
#
# LINK TO THE MOST CURRENT VERSION:
#   https://raw.githubusercontent.com/casualscripter/debian-stuff/master/usr/local/sbin/clean_upgrade
#
# CREATED:
#   01.06.2015
#
# COPYRIGHT (C):
#   2015 - Patrick Neumann
#
# LICENSE:
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
# WARRANTY:
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# HISTORY:
#   1.0 - Patrick Neumann - Initial (public) release
#===============================================================================

#=== FUNCTION ==================================================================
# NAME: error
# DESCRIPTION: Display red error messages surrounded by "Error" and "EXITING".
# PARAMETER 1: message (string)
#===============================================================================
function error () {
  /bin/echo -e "\033[01;31mError: ${1} . . . EXITING ! ! !\033[01;00m"
}

#-------------------------------------------------------------------------------
# Check, for root privileges.
#-------------------------------------------------------------------------------
if [[ 0 -ne "$( /usr/bin/id --user )" ]] ; then
  error "you need to be root"
  exit 1
fi

#-------------------------------------------------------------------------------
# The mother (Debian GNU/Linux) prefer "aptitude" over "apt-get".
#-------------------------------------------------------------------------------
if [ ! -x "/usr/bin/aptitude" ] ; then
  /usr/bin/apt-get update
  /usr/bin/apt-get install aptitude --assume-yes
fi

#-------------------------------------------------------------------------------
# Resynchronize the package index files from their sources (aptitude).
#-------------------------------------------------------------------------------
/usr/bin/aptitude update

#-------------------------------------------------------------------------------
# Install "deborphan" if missing.
#-------------------------------------------------------------------------------
if [ ! -x "/usr/bin/deborphan" ] ; then
  echo /usr/bin/aptitude install deborphan --assume-yes
fi

#-------------------------------------------------------------------------------
# Install "apt-file" if missing.
#-------------------------------------------------------------------------------
if [ ! -x "/usr/bin/apt-file" ] ; then
  /usr/bin/aptitude install apt-file -assume-yes
fi

#-------------------------------------------------------------------------------
# Resynchronize the package index files from their sources (apt-file).
#-------------------------------------------------------------------------------
/usr/bin/apt-file update

#-------------------------------------------------------------------------------
# Upgrading the HOLE system.
#-------------------------------------------------------------------------------
/usr/bin/aptitude dist-upgrade

#-------------------------------------------------------------------------------
# Clean local apt package cache.
#-------------------------------------------------------------------------------
/usr/bin/aptitude autoclean

#-------------------------------------------------------------------------------
# Purge icompletely deleted packages.
#-------------------------------------------------------------------------------
/usr/bin/dpkg --get-selections \
  | /bin/grep deinstall \
  | /usr/bin/awk '{ print $1; }' \
  | /usr/bin/xargs /usr/bin/aptitude purge --assume-yes

#-------------------------------------------------------------------------------
# Purge orphaned packages.
#-------------------------------------------------------------------------------
while REDUNDANT="$( /usr/bin/deborphan )" ; /usr/bin/test -n "${REDUNDANT}" ; do
  echo /usr/bin/aptitude purge "${REDUNDANT}" --assume-yes
done

exit 0
